compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

yarnPath: .yarn/releases/yarn-4.18.1.cjs

packageExtensions:
  "@azure/monitor-opentelemetry-exporter@1.0.0-beta.45":
    dependencies:
      "@azure/logger": "*"
