export const content = {
  'title': 'Privacy policy',
  'heading1': 'Privacy policy',
  'paragraph1': 'This privacy policy explains why we collect your personal data and what we do with it. It also explains your rights and how to enforce them.',

  'whoManagesThisServiceHeading': 'Who manages this service',
  'whoManagesThisServiceParagraph1': 'The Log and Audit service is managed by HM Courts and Tribunals Service (HMCTS), which is an executive agency of the Ministry of Justice (MoJ).',
  'whoManagesThisServiceParagraph2': 'The MoJ is known as the data controller for data protection purposes. The <a href="https://www.gov.uk/government/organisations/ministry-of-justice/about/personal-information-charter" class="govuk-link" target="_blank" rel="external noopener noreferrer" aria-label="MoJ personal information charter">MoJ personal information charter</a> explains how the MoJ processes personal data.',
  'whoManagesThisServiceParagraph3': 'As part of the MoJ, HMCTS is responsible for deciding how your personal data is used and for protecting the personal data you provide.',
  'whoManagesThisServiceParagraph4': 'More information about using this service is in the <a href="/terms-and-conditions" class="govuk-link" aria-label="terms and conditions">terms and conditions</a>.',

  'whyWeCollectDataHeading': 'Why we collect your personal data',
  'whyWeCollectDataParagraph1': 'We collect your personal data to:',
  'whyWeCollectDataItem1': 'meet legal requirements',
  'whyWeCollectDataItem2': 'evaluate our services to ensure they treat people fairly',
  'whyWeCollectDataItem3': 'make improvements to this service',
  'whyWeCollectDataParagraph2': 'Our analytical staff will use your data to create statistics. They work in the UK and your data is stored in the UK.',

  'usingYourDataHeading': 'Using your data',
  'usingYourDataParagraph3': 'We use <a href="/cookies" class="govuk-link" aria-label="cookies">cookies</a> to collect data that tells us about how you’re using this service, including:',
  'usingYourDataItem1': 'your computer, phone or tablet&rsquo;s IP address',
  'usingYourDataItem2': 'the region or town where you are using your computer, phone or tablet',
  'usingYourDataItem3': 'the web browser you use',

  'yourRightsHeading': 'Your rights',
  'yourRightsParagraph1': 'You can ask:',
  'yourRightsItem1': 'to see the personal data that we hold on you',
  'yourRightsItem2': 'to have the personal data corrected',
  'yourRightsItem3': 'to have the personal data removed or deleted (this will depend on the circumstances, for example if you decide not to continue your application)',
  'yourRightsItem4': 'that access to the personal data is restricted (for example, you can ask to have your data stored for longer and not automatically deleted)',
  'yourRightsParagraph2': 'If you want to see the personal data that we hold on you, you can:',
  'yourRightsItem5': 'complete a form to make a <a href="https://www.gov.uk/government/publications/request-your-personal-data-from-moj" class="govuk-link" target="_blank" rel="external noopener noreferrer" aria-label="subject access request">subject access request</a>. Your request goes to the MoJ as data controller.',
  'yourRightsItem6': 'write to us: Disclosure Team, Post point 10.38, 102 Petty France, London, SW1H 9AJ',
  'yourRightsParagraph3': 'You can ask for more information about:',
  'yourRightsItem7': 'agreements we have on sharing information with other organisations',
  'yourRightsItem8': 'when we are allowed to pass on personal information without telling you',
  'yourRightsItem9': 'our instructions to staff on how to collect, use or delete your personal information',
  'yourRightsItem10': 'how we check that the information we hold is accurate and up-to-date',
  'yourRightsParagraph4': 'You can contact the MoJ data protection officer, by:',
  'yourRightsItem11': 'writing to us: Post point 10.38, 102 Petty France, London, SW1H 9AJ',
  'yourRightsItem12': 'emailing: <a href="mailto:data.compliance@justice.gov.uk" class="govuk-link">data.compliance@justice.gov.uk</a>',

  'howToComplainHeading': 'How to complain',
  'howToComplainParagraph1': 'See our <a href="https://www.gov.uk/government/organisations/hm-courts-and-tribunals-service/about/complaints-procedure" class="govuk-link" target="_blank" rel="external noopener noreferrer" aria-label="complaints procedure">complaints procedure</a> if you want to complain about how we&rsquo;ve handled your personal data.',
  'howToComplainParagraph2': 'Write to: Post point 10.38, 102 Petty France, London, SW1H 9AJ',
  'howToComplainParagraph3': 'Email: <a href="mailto:data.compliance@justice.gov.uk" class="govuk-link">data.compliance@justice.gov.uk</a>',
  'howToComplainParagraph4': 'You can also complain to the <a href="https://ico.org.uk/global/contact-us" class="govuk-link" target="_blank" rel="external noopener noreferrer" aria-label="Information Commissioner&rsquo;s Office">Information Commissioner&rsquo;s Office</a> if you&rsquo;re not satisfied with our response or believe we are not processing your personal data lawfully.',
};

