---
testUrl: TEST_URL
redis:
  host: REDIS_HOST
  port: REDIS_PORT
  password: REDIS_PASSWORD
  useTLS: REDIS_USE_TLS
  enabled: USE_REDIS
  secret: REDIS_SECRET
pagination:
  maxPerPage: MAX_PER_PAGE
  maxTotal: MAX_TOTAL
services:
  lau-case-backend:
    url: LAU_CASE_BACKEND_URL
  lau-idam-backend:
    url: LAU_IDAM_BACKEND_URL
  idam-api:
    enabled: IDAM_ENABLED
    authorizationURL: IDAM_WEB_URL
    url: IDAM_API_URL
    clientID: IDAM_CLIENT_ID
    clientSecret: IDAM_CLIENT_SECRET
    callbackURL: OAUTH_CLIENT_REDIRECT
  s2s:
    enabled: S2S_ENABLED
    url: S2S_URL
featureToggles:
  ldKey: LD_SDK_KEY
  ft_deletedUsers: 'LAU_DELETED_USERS'
pages:
  userDetailsEnabled: USER_DETAILS_PAGE_ENABLED
is_dev: IS_DEV
