---
service:
  name: 'lau-frontend'
environment: 'prod'
useCSRFProtection: true
security:
  referrerPolicy: origin
appInsights:
  connectionString: false
  samplingPercentage: 100 # 100% of all telemetry will be sent to Application Insights
pagination:
  maxPerPage: 100
  maxTotal: 10000
redis:
  host: 'localhost'
  port: 6379
  password: 'dummy_password'
  useTLS: 'false'
  enabled: false
  secret: 'OVERWRITE_THIS'
  proxy: true
  resave: false
  saveUninitialized: false
  ttl: 28800 # s (8 hours)
  cookie:
    secure: false
    httpOnly: true
    sameSite: 'lax'
services:
  lau-case-backend:
    enabled: true
    url: 'http://localhost:4550'
    port: 4550
    endpoints:
      caseActivity: '/audit/caseAction'
      caseSearch: '/audit/caseSearch'
  lau-idam-backend:
    enabled: true
    url: 'http://localhost:4551'
    port: 4551
    endpoints:
      logon: '/audit/logon'
      deletedUsers: '/audit/deletedAccounts'
  idam-api:
    enabled: true
    authorizationURL: 'https://idam-web-public.aat.platform.hmcts.net/login'
    url: 'https://idam-api.aat.platform.hmcts.net'
    endpoints:
      token: '/o/token'
    clientID: 'lau'
    clientSecret: 'SECRET'
    callbackURL: 'https://localhost:4000/oauth2/callback'
  s2s:
    enabled: true
    url: 'http://rpe-service-auth-provider-aat.service.core-compute-aat.internal'
    lauSecret: 'AAAAAAAAAAAAAAAA'
  auto-suggest:
    data-file: 'data/auto-suggest-data-prod.json'
featureToggles:
  enabled: true
  ldKey: 'LD_SDK_KEY'
  ft_deletedUsers: 'LAU_DELETED_USERS'
session:
  cookieMaxAge: 30 # minutes
is_dev: true
