---
environment: 'dev'
pagination:
  maxPerPage: 10
redis:
  enabled: false
services:
  idam-api:
    enabled: false
    authorizationURL: 'http://localhost:9002/login'
    url: 'http://localhost:5000'
    clientID: 'lau'
    clientSecret: '12345678'
    callbackURL: 'https://localhost:4000/oauth2/callback'
  s2s:
    enabled: false
    url: 'http://localhost:4552'
featureToggles:
  enabled: false
