---
environment: 'dev'
pagination:
  maxRecords: 10
redis:
  enabled: false
services:
  idam:
    enabled: true
    s2sEnabled: true
    authorizationURL: 'http://localhost:9002/login'
    tokenURL: 'http://localhost:5000/o/token'
    s2sURL: 'http://localhost:4552'
    clientID: 'lau'
    clientSecret: '12345678'
    callbackURL: 'https://localhost:4000/oauth2/callback'
