---
environment: 'test'
testUrl: http://localhost:4000
pagination:
  maxPerPage: 5
services:
  idam-api:
    enabled: false
  s2s:
    enabled: false
    url: 'http://localhost:4552'
featureToggles:
  enabled: false
