export const content = {
  title: 'Terms and conditions',
  heading1: 'Terms and conditions',
  paragraph1: 'By using this service you’re agreeing to the following terms of use. This includes the <a href="/privacy" class="govuk-link" aria-label="privacy policy">privacy policy</a>.',

  whoWeAreHeading: 'Who we are',
  whoWeAreParagraph1: 'This service is managed by HMCTS.',
  whoWeAreParagraph2: 'You should check these terms and conditions regularly. We may update them at any time without notice. If you continue to use this service after the terms and conditions have changed, you are deemed to have agreed to the changes.',

  informationProvidedHeading: 'Information provided by this service',
  informationProvidedParagraph1: 'This service provides information to support your application. We cannot give legal advice on individual cases.',
  informationProvidedParagraph2: 'You should answer the questions in the service based on your circumstances, and seek legal advice if you need it.',

  dataSharingStoringHeading: 'Sharing and storing data',
  dataSharingStoringParagraph1: 'Our <a href="/privacy" class="govuk-link" aria-label="privacy policy">privacy policy</a> explains where your data is stored, and who it is shared with.',
  dataSharingStoringParagraph2: 'Our <a href="/cookies" class="govuk-link" aria-label="cookie policy">cookie policy</a> explains how this service uses and stores cookies.',

  lawsApplicableHeading: 'Laws applying to this service',
  lawsApplicableParagraph1: 'Your use of this service and any dispute arising from its use will be governed by and construed in accordance with the laws of England and Wales, including but not limited to the:',
  lawsApplicableItem1: 'Computer Misuse Act 1990',
  lawsApplicableItem2: 'Data Protection Act 1998 (until 25 May 2018)',
  lawsApplicableItem3: 'Data Protection Act 2018 (from 25 May 2018)',
  lawsApplicableItem4: 'General Data Protection Regulation',
  lawsApplicableItem5: 'Mental Capacity Act 2005',

  responsibleUseHeading: 'How to use this service responsibly',
  responsibleUseParagraph1: 'There are risks in using a shared computer (for example, in a library) to access this service. It’s your responsibility to be aware of these risks and to avoid using any computer which may leave your personal information accessible to others. You’re responsible if you choose to leave a computer unprotected while using this service.',
  responsibleUseParagraph2: 'You should take your own precautions to ensure that the way you access this service does not expose you to the risk of:',
  responsibleUseItem1: 'viruses',
  responsibleUseItem2: 'malicious computer code',
  responsibleUseItem3: 'other forms of interference which may damage your computer system',
  responsibleUseParagraph3: 'You must not misuse this service by knowingly introducing viruses, trojans, worms, logic bombs or other material which is malicious or technologically harmful. You must not attempt to gain unauthorised access to this service, the system on which it is stored, or any server, computer or database connected to it. You must not attack this site using a denial-of-service attack or a distributed denial-of-service attack.',

  disclaimerHeading: 'Disclaimer',
  disclaimerParagraph1: 'While we make every effort to keep GOV.UK up to date, we don’t provide any guarantees, conditions or warranties that the information will be:',
  disclaimerItem1: 'current',
  disclaimerItem2: 'secure',
  disclaimerItem3: 'accurate',
  disclaimerItem4: 'complete',
  disclaimerItem5: 'free from bugs or viruses',
  disclaimerParagraph2: 'We don’t publish advice on GOV.UK. You should get professional or specialist advice before doing anything on the basis of the content.',
  disclaimerParagraph3: 'We’re not liable for any loss or damage that may come from using GOV.UK. This includes:',
  disclaimerItem6: 'any direct, indirect or consequential losses',
  disclaimerItem7: 'any loss or damage caused by civil wrongs (&lsquo;tort’, including negligence), breach of contract or otherwise',
  disclaimerItem8: 'the use of GOV.UK and any websites that are linked to or from it',
  disclaimerItem9: 'the inability to use GOV.UK and any websites that are linked to or from it',
  disclaimerParagraph4: 'This applies if the loss or damage was foreseeable, arose in the normal course of things or you advised us that it might happen.',
  disclaimerParagraph5: 'This includes (but isn’t limited to) the loss of your:',
  disclaimerItem10: 'income or revenue',
  disclaimerItem11: 'salary, benefits or other payments',
  disclaimerItem12: 'business',
  disclaimerItem13: 'profits or contracts',
  disclaimerItem14: 'opportunity',
  disclaimerItem15: 'anticipated savings',
  disclaimerItem16: 'data',
  disclaimerItem17: 'goodwill or reputation',
  disclaimerItem18: 'intangible property, including loss, corruption or damage to data or any computer system',
  disclaimerItem19: 'wasted management or office time',
  disclaimerParagraph6: 'We may still be liable for:',
  disclaimerItem20: 'death or personal injury arising from our negligence',
  disclaimerItem21: 'fraudulent misrepresentation',
  disclaimerItem22: 'any other liability which cannot be excluded or limited under applicable law',

  contactHeading: 'Contact us',
  contactParagraph1: 'Phone: 0300 303 0648',
  contactParagraph2: 'Monday to Friday, 8:30am to 5:00pm.',
  contactParagraph3: '<a href="https://www.gov.uk/call-charges" class="govuk-link" target="_blank" rel="external noopener noreferrer" aria-label="Find out about call charges">Find out about call charges</a>',
};
